M48
; DRILL file KiCad 10.0.0 date 2026-03-25T22:01:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-25T22:01:15+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X115.56Y-83.765
X115.56Y-104.085
X158.74Y-83.765
X158.74Y-104.085
M30
